### ISSUE TITLE
stopped working after updating all pip packages

### ISSUE THREAD

**Issue by jpita** [lemoncheesecake/lemoncheesecake#1]
Hi,

I think I screwed up my python installation.
I updated all my pip packages and now I'm getting this error.

`Caught unexpected exception while running test: Traceback (most recent call last):
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/runner.py", line 223, in run_test
    test.callback(**test_func_params)
  File "/home/josepita/lccTests/myproject/suites/auth.py", line 21, in login
    lcc.log_info(resp.status_code)
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/runtime.py", line 124, in log_info
    get_runtime().log(LOG_LEVEL_INFO, content)
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/runtime.py", line 65, in log
    events.fire("on_log", level, content)
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/events.py", line 107, in fire
    self._call_event_type(event_type_name, lambda et: et.fire(*args, **kwargs))
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/events.py", line 94, in _call_event_type
    callback(event_type)
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/events.py", line 107, in <lambda>
    self._call_event_type(event_type_name, lambda et: et.fire(*args, **kwargs))
  File "/home/josepita/.local/lib/python2.7/site-packages/lemoncheesecake/events.py", line 62, in fire
    self._event_type_name, event_arg, i+1, type(handler_arg)
MismatchingEventArguments: For event type 'on_log', expecting type '<type 'basestring'>' for argument #2, got '<type 'int'>'
14:21:51.304`

this is the code I'm trying to run

`import requests

import lemoncheesecake.api as lcc

email = "jpita+****"
password = "****"
base_URL = "****"
expose_url = "****"

@lcc.suite("Auth tests")
class Auth:
    @lcc.test("Test login")
    def login(self):
        lcc.set_step("Get token")
        lcc.log_info("GET %s" % base_URL)
        resp = requests.get(base_URL + "/auth/login", data={"email": email, "password": password})
        lcc.log_info(resp.status_code)
        print(resp.status_code)`

according to the logs I'm using python2 but while writing code I have it set for python3 on pycharm, maybe related?
how do I run lcc with python 3?

**Comment by jpita** [comment]
never mind, was trying to print an int or so it seems :D
going to close it
