### ISSUE TITLE
AttributeError: 'set' object has no attribute 'get'

### ISSUE THREAD

**Issue by skynothing** [lemoncheesecake/lemoncheesecake#5]
What is going wrong?

ENV: Win 10 + Python 3.5

just a simple code
``` python
import lemoncheesecake.api as lcc
from lemoncheesecake.matching import *

SUITE ={u"some page"

@lcc.test(u"page")
def my_test():
    check_that(u"page","foo", equal_to("zoo"))
```

But got the error info after running "lcc run" in project folder
`Traceback (most recent call last):
  File "c:\users\test\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\test\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\Scripts\lcc.exe\__main__.py", line 9, in <module>
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\cli\main.py", line 37, in main
    return command.run_cmd(cli_args)
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\cli\commands\run.py", line 181, in run_cmd
    return run_project(load_project(), cli_args)
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\cli\commands\run.py", line 50, in run_project
    suites = get_suites_from_project(project, cli_args)
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\cli\utils.py", line 34, in get_suites_from_project
    suites = project.get_suites()
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\project.py", line 145, in get_suites
    suites = self._config.get_suites()
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\project.py", line 103, in get_suites
    return load_suites_from_directory(self._suites_dir)
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\suite\loader.py", line 253, in load_suites_from_directory
    suite = load_suite_from_file(filename)
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\suite\loader.py", line 205, in load_suite_from_file
    suite = load_suite_from_module(mod)
  File "c:\users\test\appdata\local\programs\python\python35\lib\site-packages\lemoncheesecake\suite\loader.py", line 155, in load_suite_from_module
    suite_condition = suite_info.get("conditional")
AttributeError: 'set' object has no attribute 'get'
`

**Comment by skynothing** [comment]
sorry, writing fault by myself.
